services:
  - type: web
    name: puppeteer-server
    env: node
    plan: free
    buildCommand: |
      apt-get update &&
      apt-get install -y wget gnupg ca-certificates &&
      wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
      sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' &&
      apt-get update &&
      apt-get install -y google-chrome-stable
      npm install
    startCommand: npm start
